### PR TITLE
Add the possibility to view the events on a list

### PR DESCRIPTION
**Pull request by thgcode**
This pull request adds the possibility to view the events on a list. By pressing NVDA+CONTROL+E, NVDA will show the list of events processed at that time. To save memory, only the 100 latest events are displayed.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Could you mind resolving conflicts so I can merge it as part of Event Tracker 22.12 or 23.01? Thanks.

**Comment by josephsl** [comment]
Hi,

As a follow-up: I'm wodering if we may come across other add-ons with Control+NVDA+E defined, and my general recommendation is to keep the command unassigned to take care of that scenario unless no add-ons are using this command.

Thanks.

**Comment by thgcode** [comment]
Sorry, Did not see there were conflicts, but I fixed them now and unassigned the gesture.

**Comment by josephsl** [comment]
Hi, just saw these – thanks for this work – now part of Event Tracker 22.12 (coming next week). Thanks.

**Pull request merged**
